name: docker-dev

services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-app}
      - MYSQL_USER=${MYSQL_USER:-app}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-app}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -p${MYSQL_ROOT_PASSWORD:-root} || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 20
    labels:
      - dev.orbstack.domains=mysql.orb.local

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-app}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      - ./volumes/postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 20
    labels:
      - dev.orbstack.domains=postgres.orb.local
    logging:
      driver: "none"

  redis:
    image: redis:7.4-alpine
    container_name: redis
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REDIS_APPENDONLY=${REDIS_APPENDONLY:-yes}
    command: ["redis-server", "--appendonly", "${REDIS_APPENDONLY:-yes}"]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ./volumes/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
    labels:
      - dev.orbstack.domains=redis.orb.local

  # # Convex self-hosted (backend + dashboard)
  convex-backend:
    image: ghcr.io/get-convex/convex-backend:33cef775a8a6228cbacee4a09ac2c4073d62ed13
    container_name: convex-backend
    restart: unless-stopped
    stop_grace_period: 10s
    stop_signal: SIGINT
    env_file:
      - .env
    environment:
      - INSTANCE_NAME=${CONVEX_INSTANCE_NAME:-dev-instance}
      - INSTANCE_SECRET=${CONVEX_INSTANCE_SECRET:-}
      - CONVEX_CLOUD_ORIGIN=${CONVEX_CLOUD_ORIGIN:-http://localhost:${CONVEX_BACKEND_PORT:-3210}}
      - CONVEX_SITE_ORIGIN=${CONVEX_SITE_ORIGIN:-http://localhost:${CONVEX_PROXY_PORT:-3211}}
      - POSTGRES_URL=${POSTGRES_URL:-postgresql://postgres:admin@postgres:5432}
      - RUST_LOG=${RUST_LOG:-info}
      - DO_NOT_REQUIRE_SSL=${DO_NOT_REQUIRE_SSL:-true}
    ports:
      - "${CONVEX_BACKEND_PORT:-3210}:3210"
      - "${CONVEX_PROXY_PORT:-3211}:3211"
    volumes:
      - ./volumes/convex:/convex/data
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:3210/version > /dev/null"]
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 30
    labels:
      - dev.orbstack.domains=convex.api.orb.local,convex.site.orb.local
    logging:
      driver: "none"

  convex-dashboard:
    image: ghcr.io/get-convex/convex-dashboard:latest
    container_name: convex-dashboard
    restart: unless-stopped
    stop_grace_period: 10s
    stop_signal: SIGINT
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_DEPLOYMENT_URL=${NEXT_PUBLIC_DEPLOYMENT_URL:-https://convex-backend.docker-dev.orb.local}
    ports:
      - "${CONVEX_DASHBOARD_PORT:-6791}:6791"
    depends_on:
      convex-backend:
        condition: service_healthy
    labels:
      - dev.orbstack.domains=convex.dashboard.orb.local

  # Local Google Cloud Storage emulator
  gcs:
    image: fsouza/fake-gcs-server:latest
    container_name: gcs
    restart: unless-stopped
    env_file:
      - .env
    # Using HTTP on port 4443; "-public-host" set for nice OrbStack domain callbacks
    command:
      [
        "-scheme",
        "http",
        "-backend",
        "memory",
        "-port",
        "${GCS_PORT:-4443}",
        "-public-host",
        "gcs.docker-dev.orb.local:${GCS_PORT:-4443}",
      ]
    ports:
      - "${GCS_PORT:-4443}:4443"
    volumes:
      - ./volumes/gcs/data:/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- http://localhost:4443/storage/v1/b > /dev/null || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 20
    labels:
      - dev.orbstack.domains=gcs.orb.local
    logging:
      driver: "none"

  local-smtp:
    container_name: local-smtp
    image: axllent/mailpit
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "${SMTP_WEB_PORT:-8326}:8025" # web ui
      - "${SMTP_PORT:-1025}:1025" # smtp port
    logging:
      driver: "none"
    labels:
      - dev.orbstack.domains=mail.orb.local
